services:
  web:
    image: php:8.4-apache
    container_name: bridge_web
    ports:
      - "8082:80"
    volumes:
      - ./bridgevojvodina-laravel:/var/www/html
    networks:
      - bridge-net
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    command: >
      sh -c "apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev && docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-ext-install mysqli pdo pdo_mysql gd && sed -i 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/000-default.conf && a2enmod rewrite && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: bridge_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bridge-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bridge_pma
    restart: always
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - bridge-net

volumes:
  db_data:

networks:
  bridge-net:
    driver: bridge
